### ISSUE TITLE
겜블 설치시...

### ISSUE THREAD

**Issue by Laeng** [HmHmmHm/EconomyGamble#1]
겜블 설치시 좌표값만 저장을 하는것 같아요....
그런데... 멀티월드를 사용하게되면.... A 월드에 설치한 겜블이....
B 월드에서 A 월드에 설치된 겜블 위치에서 금괴가 스폰이 되요!

제가 이부분을 좌표값만 저장하지 않고 월드값까지 저장할수 있도록 조금 수정해서 여기에 업데이트 하려고 하는데.... 참여해도 될까요?

**Comment by HmHmmHm** [comment]
@Laeng 물론입니다. 변경할 내용을 작성 후 Pull Request를 걸어주시면 됩니다
