### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by ghost** [HmHmmHm/EconomyGamble#2]
Cause in MP 1.6. It crashed my server

**Comment by HmHmmHm** [comment]
Ok, I'll fix that problem, anyway are you american?
can you help us translate for english to better english?

**Comment by ifvictr** [comment]
@HmHmmHm He's not American. Anyways if you need an English translator you can always call me. @mention me for more information regarding this.

**Comment by HmHmmHm** [comment]
Oh! thanks for your cooperation...!!
We want to share for "pocketmine.net" forum

https://github.com/if-Team/PMMP-Plugins

@Gamecrafter 
I'll apply the permissions for you
and I'll @mention you :p!

**Comment by ifvictr** [comment]
@HmHmmHm What permissions?

**Comment by HmHmmHm** [comment]
@Gamecrafter a PMMP-Plugins repository Permission,
does not need permission? just fine pull request?

**Comment by ifvictr** [comment]
@HmHmmHm I think pull requests will be fine. :wink: Where should I start?

**Comment by HmHmmHm** [comment]
@Gamecrafter ok '~'! i'll @mention for you

**Comment by ifvictr** [comment]
@HmHmmHm Okay, just mention me at the place(s) you want me to translate, I'll try to make a PR to translate ASAP.

**Comment by HmHmmHm** [comment]
fixed b8fb2311af4de4fc6bbf05784bf99c5dbfe3bafe
